# Generated by Django 2.1.5 on 2020-12-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('online payment', 'online payment')], default='cash on delivery', max_length=20),
        ),
    ]
