# Generated by Django 2.1.5 on 2021-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_buk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buk',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
