# Generated by Django 2.1.5 on 2021-01-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210111_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buk',
            old_name='email_id',
            new_name='Email_id',
        ),
        migrations.RenameField(
            model_name='buk',
            old_name='mobile_number',
            new_name='Mobile_number',
        ),
        migrations.RenameField(
            model_name='buk',
            old_name='name',
            new_name='Name',
        ),
    ]
