# Generated by Django 2.1.5 on 2021-01-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210111_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buk',
            old_name='Book_description',
            new_name='book_description',
        ),
        migrations.RenameField(
            model_name='buk',
            old_name='Email_id',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='buk',
            old_name='Mobile_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='buk',
            old_name='Name',
            new_name='name',
        ),
    ]
